## Datatypes and Attributes

In [4]:
## Numpy main datatype is ndarray

import numpy as np

a1 = np.array([1,2,3])
a1


array([1, 2, 3])

In [19]:
a1.shape

(3,)

In [5]:
type(a1)

numpy.ndarray

In [7]:
a2=np.array([[1, 2.6, 3.4],
             [4.5, 3.2, 2.8]])
a2

array([[1. , 2.6, 3.4],
       [4.5, 3.2, 2.8]])

In [8]:
a2.shape

(2, 3)

In [0]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              
              [[1,2,4],
               [4,6,9],
               [6,4,2]]])

In [17]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 4],
        [4, 6, 9],
        [6, 4, 2]]])

In [18]:
a3.shape

(2, 3, 3)

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [21]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [22]:
## create a dataframe from numpy array

import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.6  3.4
1  4.5  3.2  2.8

## Creating Arrays

In [26]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [29]:
ones.dtype

dtype('float64')

In [27]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
zeros.dtype

dtype('float64')

In [32]:
rangearr = np.arange(0,10,2)
rangearr

array([0, 2, 4, 6, 8])

In [33]:
rangearr = np.arange(0,10)
rangearr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
randomarr = np.random.randint(0,10,size=(3,5))
randomarr

array([[4, 1, 0, 4, 7],
       [9, 8, 6, 8, 8],
       [3, 2, 7, 2, 6]])

In [40]:
randomarr.size,  randomarr.shape

(15, (3, 5))

In [44]:
randomarr2 = np.random.random((5,3))
randomarr2

array([[0.62189821, 0.43425482, 0.87123418],
       [0.2773741 , 0.35252947, 0.01403279],
       [0.56114753, 0.59727605, 0.49574178],
       [0.92776714, 0.3718475 , 0.36043184],
       [0.53748417, 0.19310227, 0.12362455]])

In [50]:
## pseudo-random numbers
## random numbers keep aligned with the seed, preserve random numbers while executed multiple times
np.random.seed(0)
randomarr3=np.random.randint(10, size=(5,3))
randomarr3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [54]:
np.random.seed(7)
randomarr4=np.random.random((5,3))
randomarr4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing Arrays and Matrices

In [58]:
np.unique(randomarr4)

array([0.06593635, 0.07205113, 0.07630829, 0.26843898, 0.2881456 ,
       0.38094113, 0.43840923, 0.4998825 , 0.50112046, 0.53849587,
       0.67923   , 0.72346518, 0.77991879, 0.80373904, 0.97798951])

In [59]:
np.unique(randomarr3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1

array([1, 2, 3])

In [61]:
a2

array([[1. , 2.6, 3.4],
       [4.5, 3.2, 2.8]])

In [62]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 4],
        [4, 6, 9],
        [6, 4, 2]]])

In [63]:
a1[0]  ,  a2[0]

(1, array([1. , 2.6, 3.4]))

In [64]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a2[1]

array([4.5, 3.2, 2.8])

In [66]:
a3[:2,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 6]]])

### Manipulating and comparing arrays

In [67]:
a1

array([1, 2, 3])

In [69]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [70]:
a1+ones

array([2., 3., 4.])

In [71]:
a1-ones

array([0., 1., 2.])

In [72]:
a1 * ones

array([1., 2., 3.])

In [73]:
a2

array([[1. , 2.6, 3.4],
       [4.5, 3.2, 2.8]])

In [74]:
a1 * a2

array([[ 1. ,  5.2, 10.2],
       [ 4.5,  6.4,  8.4]])

In [75]:
np.square(a2)

array([[ 1.  ,  6.76, 11.56],
       [20.25, 10.24,  7.84]])

In [76]:
np.add(a1, ones)

array([2., 3., 4.])

In [77]:
np.mod(a1, 2)

array([1, 0, 1])

In [78]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [79]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

In [80]:
np.sum(a1)

6

In [81]:
np.max(a2)

4.5

In [82]:
np.min(a2)

1.0

In [83]:
np.std(a2)

1.049470766095411

In [84]:
np.var(a2)

1.101388888888889

In [85]:
np.sqrt(np.var(a2))

1.049470766095411

## Reshape and Transpose

In [86]:
a2

array([[1. , 2.6, 3.4],
       [4.5, 3.2, 2.8]])

In [87]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 4],
        [4, 6, 9],
        [6, 4, 2]]])

In [90]:
a2reshape = a2.reshape(2 , 3,  1)
a2reshape

array([[[1. ],
        [2.6],
        [3.4]],

       [[4.5],
        [3.2],
        [2.8]]])

In [93]:
m = a2reshape * a3
m

array([[[ 1. ,  2. ,  3. ],
        [10.4, 13. , 15.6],
        [23.8, 27.2, 30.6]],

       [[ 4.5,  9. , 18. ],
        [12.8, 19.2, 28.8],
        [16.8, 11.2,  5.6]]])

In [94]:
m.shape

(2, 3, 3)

In [95]:
## transpose
a2.T

array([[1. , 4.5],
       [2.6, 3.2],
       [3.4, 2.8]])

In [96]:
a2.shape,  a2.T.shape

((2, 3), (3, 2))

In [97]:
a3.shape,  a3.T.shape

((2, 3, 3), (3, 3, 2))

## Dot Product

In [0]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [99]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [100]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [101]:
mat1.shape,  mat2.shape

((5, 3), (5, 3))

In [102]:
## Element-wise multiplication (Hadamard product)

mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [104]:
## Dot product 

np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [105]:
mat1.shape,  mat2.T.shape

((5, 3), (3, 5))

In [106]:
mat1.T.shape,  mat2.shape

((3, 5), (5, 3))

In [107]:
np.dot(mat1.T,  mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

## Dot product example

In [108]:
np.random.seed(0)

## number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [109]:
## create weekly sales dataframe

weekly_sales = pd.DataFrame(sales_amounts, index=['Mon', 'Tue', 'Wed', 'Thurs', 'Fri'], 
                            columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [110]:
## create prices array

prices= np.array([10, 8, 12])
prices

array([10,  8, 12])

In [112]:
## create prices dataframe

pricesdf = pd.DataFrame(prices.reshape(1,3), index=['Price'], 
                        columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
pricesdf

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [113]:
total_sales = np.dot(prices, sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [115]:
## create daily total sales

pricesdf.shape,  weekly_sales.shape

((1, 3), (5, 3))

In [117]:
daily_sales = pricesdf.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thurs  Fri
Price  240  138  458    232  142

In [0]:
weekly_sales['Total'] = daily_sales.T

In [120]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Mon               12             15              0    240
Tue                3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

In [121]:
## comparison operators

a1 >  a2

array([[False, False, False],
       [False, False,  True]])

In [122]:
a1 > 5

array([False, False, False])

In [123]:
a1 < 3

array([ True,  True, False])

## Sorting arrays

In [124]:
randomarr1 = np.random.randint(10, size=(3,5))
randomarr1

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [125]:
np.sort(randomarr1)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [126]:
np.argsort(randomarr1)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [127]:
np.argmax(randomarr1)

4

In [128]:
np.argmin(randomarr1)

9

In [129]:
np.argmax(randomarr1, axis=0)

array([1, 1, 1, 0, 0])

In [130]:
np.argmax(randomarr1, axis=1)

array([4, 1, 1])

## Converting images into numpy array

In [131]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
filepath='/content/gdrive/My Drive/'

In [0]:
from matplotlib.image import imread
panda = imread(filepath+'panda.png')

In [138]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [139]:
panda.shape,  panda.size,  panda.ndim

((2330, 3500, 3), 24465000, 3)

In [140]:
type(panda)

numpy.ndarray